booking_system/authentication_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login', views.login_user, name='login_user'),
    path('sign-up', views.register_user, name='register_user'),
    path('logout', views.logout_user, name='logout_user'),
    path('reset-password', auth_views.PasswordResetView.as_view(template_name="authentication_app/reset_password.html"), 
         name="reset_password"),
    path('reset-password-sent', auth_views.PasswordResetDoneView.as_view(template_name="authentication_app/reset_password_sent.html"), 
         name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="authentication_app/set_password.html"), 
         name="password_reset_confirm"),
    path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name="authentication_app/reset_password_complete.html"), 
         name="password_reset_complete"),
]

booking_system/booking_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication_app.urls')),
    path('', include('myapp.urls')),
]

booking_system/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name='home'),
    path('book', views.book, name='book'),
    path('book/<int:id_building>', views.book_building, name='book_building'),
    path('book/<int:id_building>/manage-booking', views.book_room, name='book_room'),
    path('manage-booking', views.manage_booking, name='manage_booking'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
]

booking_system/authentication_app/models.py
from django.db import models

# Create your models here.

booking_system/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Building(models.Model):
    id = models.AutoField(primary_key=True)
    building_name = models.CharField(max_length=50)

    def __str__(self):
        name = (' ').join(str(self.building_name).split('_'))
        return name


class Room(models.Model):
    id = models.AutoField(primary_key=True)
    room_name = models.CharField(max_length=50) 
    building = models.ForeignKey(Building, on_delete=models.CASCADE)

    def __str__(self):
        return self.room_name
    


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default=None)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    start_hour = models.TimeField(default='08:00:00')
    end_hour = models.TimeField(default='10:00:00')
    marge = models.IntegerField(null=True)

    def __str__(self):
        room = (' ').join(str(self.room).split('_')).title()
        start_date_str = self.start_date.strftime('%B %dth, %Y')
        start_hour_str = self.start_hour.strftime('%H:%M')
        end_hour_str = self.end_hour.strftime('%H:%M')
        return f"{room} booked on {start_date_str} from {start_hour_str} to {end_hour_str}"
    

booking_system/authentication_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    email = forms.EmailField()


    class Meta:
        model = User
        fields = ["email", "username", "password1", "password2"]

booking_system/myapp/forms.py
from django import forms
from .models import Booking



class BookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['room', 'start_date', 'start_hour', 'end_hour']

booking_system/authentication_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.
@csrf_exempt
def login_user(request):
    if request.method == "POST":

        

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            messages.success(request, ("There was an error logging in, Try again!"))
            return redirect('/login')
        
    else:
        if request.user.is_anonymous:
            return render(request, "authentication_app/login.html", {})
            
        else:
            messages.success(request, ("You are already logged in!"))
            return redirect('/home')


    

def register_user(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/home')
        
        else:
            messages.success(request, ("There was an error, Try again!"))
            return redirect('/sign-up')
    else:
        return render(request, "authentication_app/register.html", {})
    


def logout_user(request):
    logout(request)
    return redirect('login_user')
    

booking_system/myapp/views.py
from django.shortcuts import render, redirect
from .models import Building, Room, Booking
from .forms import BookingForm
from django.contrib import messages


# Create your views here.
def home(request):
    return render(request, 'myapp/home.html')

def book(request):
    buildings = Building.objects.all()
    
    return render(request, 'myapp/book.html', {'buildings': buildings})

def book_building(request, id_building):
    first_name = request.user.first_name
    buildings = Building.objects.all()
    rooms = Room.objects.filter(building_id=id_building)

   
    context = {
        'first_name': first_name, 
        'buildings': buildings,
        'id_building': id_building,
        'rooms': rooms
    }
    return render(request, 'myapp/book.html', context)

def book_room(request, id_building):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            room_id = form.cleaned_data['room']
            start_date = form.cleaned_data['start_date']
            start_hour = form.cleaned_data['start_hour']
            end_hour = form.cleaned_data['end_hour']


            # Create a new Booking object and save it to the database
            booking = Booking(
                user=request.user,  # Assuming the user is logged in
                room=room_id,
                start_date=start_date,
                start_hour=start_hour,
                end_hour=end_hour
            )
            booking.save()

            # Redirect to a success page or home page
            messages.success(request, ("Booking seccessful"))
            return render(request, 'myapp/manage_booking.html')
        else:
            messages.success(request, ("There was an error Booking, Try again!"))
            return redirect('/book')
   
    else:
        return render(request, 'myapp/manage_booking.html')

def manage_booking(request):
    user_id = request.user.id
    bookings = Room.objects.filter(id=user_id)

    return render(request, 'myapp/manage_booking.html', {"bookings":bookings})


def contact(request):
    return render(request, 'myapp/contact.html')

def about(request):
    return render(request, 'myapp/about.html')

booking_system/authentication_app/templates/authentication_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

  {% include 'authentication_app/navbar.html' %}

  <div class="container">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center">Account Login</h5><br>
            <form method="post">
              <div class="mb-3 d-flex justify-content-center">
                <input type="text" class="form-control" id="username" name="username" placeholder="Username">
              </div>
              <div class="mb-3 d-flex justify-content-center">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
              </div>
              {% csrf_token %}
              {% if messages %}
                  {% for message in messages %}
                      <span style="color: red">{{ message }}</span>
                  {% endfor %}
              {% endif %}

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Login Now</button>
              </div>
              
            </form>
            <div class="mt-3 text-end">
              <a href="{% url 'reset_password' %}">Forget password?</a>
            </div>
  
            <div class="row justify-content-center">
              <div class="col-4">
                <hr>
              </div>
              <div class="col-auto">
                or
              </div>
              <div class="col-4">
                <hr>
              </div>
            </div>
  
            <div class="mt-3 text-center">
              <span>Are you new? </span> <a href="{% url 'register_user' %}">Create account</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/authentication_app/templates/authentication_app/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      
      <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item me-5">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item me-5">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>

          <li class="nav-item me-5">
            <a class="nav-link" href="">About</a>
          </li>
        </ul>
      </div>
      
      <!-- Place the sign-out button here
      <div class="ml-auto">
        <form class="form-inline my-2 my-lg-0" action="{% url 'logout_user' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Log Out</button>
        </form>
      </div> -->
      
    </div>
  </nav>
  

booking_system/authentication_app/templates/authentication_app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sign up</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

  <div class="container">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center">Sign Up</h5><br>
            <form method="post" class="form">
              
              <div class="mb-3 d-flex justify-content-center">
                <input type="text" class="form-control" name="email" placeholder="Email">
              </div>

              <div class="mb-3 d-flex justify-content-center">
                <input type="text" class="form-control" name="username" placeholder="Username">
              </div>


              <div class="mb-3 d-flex justify-content-center">
                <input type="password" class="form-control" id="password" name="password1" placeholder="Password">
              </div>


              <div class="mb-3 d-flex justify-content-center">
                <input type="password" class="form-control" id="password" name="password2" placeholder="Confirm Password">
              </div>
              {% csrf_token %}
              {% if messages %}
                  {% for message in messages %}
                      <span style="color: red">{{ message }}</span>
                  {% endfor %}
              {% endif %}

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Sign Up</button>
              </div>
              
            </form>
           
              <br>
            <div class="row justify-content-center">
              <div class="col-4">
                <hr>
              </div>
              <div class="col-auto">
                or
              </div>
              <div class="col-4">
                <hr>
              </div>
            </div>
  
            <div class="mt-3 text-center">
              <a href="{% url 'login_user' %}">Login</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/authentication_app/templates/authentication_app/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reset Password</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

    {% include 'authentication_app\navbar.html' %}

  <div class="container">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            
            <h5 class="card-title text-center">Forgot Password</h5>
            <p style="text-align: center;">Enter your email and we'll send you a link to reset your password</p>
            <form method="post">
     

              {% csrf_token %}
              {% if messages %}
                  {% for message in messages %}
                      <span style="color: red">{{ message }}</span>
                  {% endfor %}
              {% endif %}
                
              <div class="mb-4 d-flex justify-content-center">
                <input type="text" class="form-control" name="email" placeholder="Email"><br>
              </div>
             

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
              
            </form>
           
      
  
           
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/authentication_app/templates/authentication_app/reset_password_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Password Set</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

    {% include 'authentication_app\navbar.html' %}
    
    <div class="container mt-4">
    <h3>Password reset complete</h3><br>
    
    Your password has been set. You may go ahead and log in now. <br>
    
    <a href="{% url 'login_user' %}">Log in</a>

    </div>

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/authentication_app/templates/authentication_app/reset_password_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Centered Form</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

    {% include 'authentication_app\navbar.html' %}
    
    <div class="container mt-4">
    <h3>Password reset sent</h3><br>
    
        We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
        
        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
  
    </div>

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/authentication_app/templates/authentication_app/set_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Set Password</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

  {% load static %}

  <link rel="stylesheet" href="{% static 'authentication_app/style_login.css' %}">

</head>
<body >

    {% include 'authentication_app\navbar.html' %}

  <div class="container">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            
            <h5 class="card-title text-center">Enter new password</h5>
            <p style="text-align: center;">Please enter your new password twice so we can verify you typed it in correctly.</p>
            <form method="post">
     

              {% csrf_token %}
              
                
              <div class="mb-3 d-flex justify-content-center">
                <input type="password" class="form-control" id="password" name="new_password1" placeholder="Password">
              </div>


              <div class="mb-3 d-flex justify-content-center">
                <input type="password" class="form-control" id="password" name="new_password2" placeholder="Confirm Password">
              </div>
             

              <div class="text-center">
                <button type="submit" class="btn btn-primary">Reset Password</button>
              </div>
              
            </form>
           
      
  
           
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  

<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

booking_system/myapp/templates/myapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    {% load static %}

  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">

</head>
<body>
    {% include 'myapp/navbar.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>


              {% if messages %}
                  {% for message in messages %}
                      {{ message }}
                  {% endfor %}
              {% endif %}

          


</body>
</html>

booking_system/myapp/templates/myapp/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    {% load static %}

    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">

</head>
<body>
{% include 'myapp/navbar.html' %}
{% if messages %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    {% for message in messages %}
                        <div class="alert alert-info">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}


<div class="container mt-4 building-container-centered">
    <div class="row justify-content-center align-items-center"  id="mainContainer" style="min-height: 100vh;">
        <div class="col-md-6">
            <div class="card" style="background-image: linear-gradient(to right, #edeef8, #f98edc)">
                <div class="card-body">
                <div class="box_full">

                    <div class="building-container">
                        {% for building in buildings|slice:"3" %}
                            <div class="building-box">
                                <h2 class="building-name">{{ building }}</h2>
                                <p class="room-count">Rooms available : {{ building.room_set.count }}</p>
                                <a href="{% url 'book_building' id_building=building.id %}" class="btn btn-primary">Book Room</a>
                            </div><br>
                        {% endfor %}
                    </div>

                </div>
                </div>
            </div>
        </div>
        
        


        <!-- Form to book a room -->
        {% if id_building %}
        <div class="col-md-6">
            <form id="booking-form" method="post" action="{% url 'book_room' id_building=id_building %}">
                <!-- Building name (hidden field populated dynamically) -->
                <input type="hidden" id="building-name" name="building-name" value="{{ id_building }}">

                <!-- Room selection -->
                <div class="form-group">
                    <label for="room">Select a Room in Building 
                        {% if id_building == 1 %}
                            A
                        {% elif id_building == 2 %}
                            B
                        {% elif id_building == 3 %}
                            C
                        {% endif %}
                    :</label>
                    <select class="form-control" id="room" name="room">
                        {% for room in rooms %}
                            <option value="{{ room.id }}">{{ room.id }}</option>
                        {% endfor %}
                    </select>
                </div>
                

                <!-- Date -->
                <div class="form-group">
                    <label for="date">Date:</label>
                    <input type="date" class="form-control" id="start_date" name="start_date">

                </div>

                <!-- Start hour -->
                <div class="form-group">
                    <label for="start-hour">Start Hour:</label>
                    <input type="time" class="form-control" id="start_hour" name="start_hour">
                </div>

                <!-- End hour -->
                <div class="form-group">
                    <label for="end-hour">End Hour:</label>
                    <input type="time" class="form-control" id="end_hour" name="end_hour">
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary">Book Room</button>
                {% csrf_token %}
            </form>
        </div>

        {% endif %}

    </div>
</div>

    
    
    



</div>
</body>
</html>

booking_system/myapp/templates/myapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    {% load static %}

  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">

</head>
<body>
    {% include 'myapp/navbar.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>


              {% if messages %}
                  {% for message in messages %}
                      {{ message }}
                  {% endfor %}
              {% endif %}

          


</body>
</html>

booking_system/myapp/templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    {% load static %}

  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">

</head>
<body>
    {% include 'myapp/navbar.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>


              {% if messages %}
                  {% for message in messages %}
                      {{ message }}
                  {% endfor %}
              {% endif %}

          


</body>
</html>

booking_system/myapp/templates/myapp/manage_booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage booking</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    {% load static %}

    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">

</head>
<body>
{% include 'myapp/navbar.html' %}
{% if messages %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    {% for message in messages %}
                        <div class="alert alert-info">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}

    {% if bookings %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
               
                <div class="container mt-4 building-container-centered">
                    <div class="row justify-content-center align-items-center"  id="mainContainer" style="min-height: 100vh;">
                        <div class="col-md-6">
                            <div class="card" style="background-image: linear-gradient(to right, #edeef8, #f98edc)">
                                <div class="card-body">
                                <div class="box_full">
                
                                    <div class="building-container">
                                        {% for building in buildings|slice:"3" %}
                                            <div class="building-box">
                                                <h2 class="building-name">{{ building }}</h2>
                                                <p class="room-count">Rooms available : {{ building.room_set.count }}</p>
                                                <a href="{% url 'book_building' id_building=building.id %}" class="btn btn-primary">Book Room</a>
                                            </div><br>
                                        {% endfor %}
                                    </div>
                
                                </div>
                                </div>
                            </div>
                        </div>
                        


            </div>
        </div>
    </div>
{% endif %}

</div>
</body>
</html>

booking_system/myapp/templates/myapp/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      
      <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item me-5">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item me-5">
            <a class="nav-link" href="{% url 'book' %}">Book</a>
          </li>
          <li class="nav-item me-5">
            <a class="nav-link" href="{% url 'manage_booking' %}">Manage Booking</a>
          </li>
          <li class="nav-item me-5">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>

          <li class="nav-item me-5">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
        </ul>
      </div>
      
      <!-- Place the sign-out button here -->
      <div class="ml-auto">
        <form class="form-inline my-2 my-lg-0" action="{% url 'logout_user' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Log Out</button>
        </form>
      </div>
      
    </div>
  </nav>
  